name: 'CI-CD'

on:
  pull_request:
    branches: [main]

jobs:
  backend-build-test:
    name: Back-end build and test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    defaults:
      run:
        working-directory: back
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Install Maven dependencies
        run: mvn install
      - name: Run tests
        run: mvn verify
      - name: Add back-end coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: back/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 60
          title: Back-end Code Coverage
          update-comment: true
          pass-emoji: ':green_circle:'
          fail-emoji: ':red_circle:'
      # must fail if minimum is not reached

  frontend-build-test:
    name: Front-end build and test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    defaults:
      run:
        working-directory: front
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js 16.10.0
        uses: actions/setup-node@v4
        with:
          node-version: '16.10.x'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test:ci
      - name: Front-end Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: front/coverage/code-coverage.xml
          badge: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'
      - name: Add Front-end Coverage PR to Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
      # must fail if minimum is not reached

#  backend-quality:
#    name: Back-end code quality
#    runs-on: ubuntu-latest
#    permissions: read-all
#    defaults:
#      run:
#        working-directory: back
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#      - name: Scan with SonarQube
#        uses: sonarsource/sonarqube-scan-action@master
#        env:
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACK }}
#          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
# If you wish to fail your job when the Quality Gate is red, uncomment the
# following lines. This would typically be used to fail a deployment.
# - uses: sonarsource/sonarqube-quality-gate-action@master
#   timeout-minutes: 5
#   env:
#     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACK }}

#  frontend-quality:
#    name: Front-end code quality
#    runs-on: ubuntu-latest
#    permissions: read-all
#    defaults:
#      run:
#        working-directory: front
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#      - name: Scan with SonarQube
#        uses: sonarsource/sonarqube-scan-action@master
#        env:
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONT }}
#          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        # If you wish to fail your job when the Quality Gate is red, uncomment the
        # following lines. This would typically be used to fail a deployment.
        # - uses: sonarsource/sonarqube-quality-gate-action@master
        #   timeout-minutes: 5
        #   env:
        #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONT }}

  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Back-end build and push
        uses: docker/build-push-action@v5
        with:
          context: back
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bobapp:backend
      - name: Front-end build and push
        uses: docker/build-push-action@v5
        with:
          context: front
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bobapp:frontend
