name: 'CI'

on:
  pull_request:
    branches: [main]

permissions:
  checks: write

jobs:
  backend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Install Maven dependencies
        run: mvn install
      - name: Run tests
        run: mvn verify
      - name: Jacoco report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v5.0
        with:
          coverage_results_path: back/target/site/jacoco/jacoco.xml
          coverage_report_name: Coverage
          coverage_report_title: JaCoCo
          publish_only_summary: true

  frontend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js 16.10.0
        uses: actions/setup-node@v4
        with:
          node-version: '16.10.x'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test:ci
