name: 'CI'

on:
  pull_request:
    branches: [main]

jobs:
  backend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Install Maven dependencies
        run: mvn install
      - name: Run tests
        run: mvn verify
      - name: Back test report
        uses: phoenix-actions/test-reporting@v9
        id: back-test-report
        if: success() || failure()
        with:
          name: Java Tests
          path: back/target/site/jacoco/jacoco.xml
          reporter: java-junit

  frontend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js 16.10.0
        uses: actions/setup-node@v4
        with:
          node-version: '16.10.x'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test:ci
      - name: Front test report
        uses: phoenix-actions/test-reporting@v9
        id: front-test-report
        if: success() || failure()
        with:
          name: JEST Tests
          path: front/coverage/bobapp/code-coverage.xml
          reporter: jest-junit
