name: 'Test report'

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

jobs:
  back-report:
    runs-on: ubuntu-latest
    steps:
      - name: Generate back report
        uses: phoenix-actions/test-reporting@v9
        id: back-tests-report
        with:
          artifact: back-tests-results
          name: Java Tests
          path: '*.xml'
          reporter: java-junit

  front-report:
    runs-on: ubuntu-latest
    steps:
      - name: Generate front report
        uses: phoenix-actions/test-reporting@v9
        id: front-tests-report
        with:
          artifact: front-tests-results
          name: JEST Tests
          path: '*.xml'
          reporter: jest-junit